import { Part, PART_CATEGORY, PC_TYPE, PrebuiltConfig } from './types';

export const CATEGORY_GUIDES: Record<PART_CATEGORY, { title: string; description: string; importance: string }> = {
  [PART_CATEGORY.CPU]: {
    title: "The Brain (Central Processing Unit)",
    description: "Executes instructions and orchestrates all other components. Faster CPUs handle calculations and logic quicker.",
    importance: "Critical for gaming physics, video editing, and compiling code."
  },
  [PART_CATEGORY.MAINBOARD]: {
    title: "The Nervous System (Motherboard)",
    description: "Connects all components together. Determines which CPU and RAM you can use.",
    importance: "Dictates upgradability and connectivity (USB ports, WiFi)."
  },
  [PART_CATEGORY.RAM]: {
    title: "Short-term Memory (Random Access Memory)",
    description: "Stores data currently in use for fast access by the CPU. Cleared when power is off.",
    importance: "More RAM allows multitasking and running heavy applications smoothly."
  },
  [PART_CATEGORY.GPU]: {
    title: "Visual Cortex (Graphics Processing Unit)",
    description: "Renders images, video, and 3D graphics. The most expensive part of a gaming PC.",
    importance: "Essential for gaming, 3D rendering, and AI tasks."
  },
  [PART_CATEGORY.STORAGE]: {
    title: "Long-term Memory (SSD/HDD)",
    description: "Stores your OS, games, and files permanently.",
    importance: "NVMe SSDs drastically reduce load times compared to older HDDs."
  },
  [PART_CATEGORY.PSU]: {
    title: "The Heart (Power Supply Unit)",
    description: "Converts wall power to clean DC power for components.",
    importance: "A bad PSU can destroy your system. Never cheap out here."
  },
  [PART_CATEGORY.CASE]: {
    title: "The Skeleton (Chassis)",
    description: "Houses and protects all components. Affects airflow and cooling.",
    importance: "Determines size and aesthetics of your build."
  },
  [PART_CATEGORY.COOLER]: {
    title: "Thermoregulation (CPU Cooler)",
    description: "Dissipates heat generated by the CPU to prevent overheating.",
    importance: "Required for high-performance CPUs to maintain speed."
  },
  [PART_CATEGORY.NIC]: {
    title: "Network Interface",
    description: "Handles high-speed network connections, critical for servers.",
    importance: "Essential for server bandwidth management."
  },
  [PART_CATEGORY.MONITOR]: {
    title: "The Display",
    description: "Visualizes the output. High refresh rates (Hz) are smoother.",
    importance: "The interface between you and the computer's power."
  }
};

export const MOCK_PARTS: Part[] = [
  // --- CPU (Expanded Levels) ---
  {
    id: 'cpu-entry-1',
    name: 'Intel Core i3-13100F',
    category: PART_CATEGORY.CPU,
    price: 110,
    image: 'https://picsum.photos/200/200?random=101',
    brand: 'Intel',
    specs: { socket: 'LGA1700', cores: 4, wattage: 58, memoryType: 'DDR4' },
    vendors: [{ name: 'Amazon', url: '#', price: 110, inStock: true }],
    rating: 4.3
  },
  {
    id: 'cpu-1',
    name: 'Intel Core i5-13400F',
    category: PART_CATEGORY.CPU,
    price: 200,
    image: 'https://picsum.photos/200/200?random=1',
    brand: 'Intel',
    specs: { socket: 'LGA1700', cores: 10, wattage: 65, memoryType: 'DDR5' },
    vendors: [
        { name: 'Amazon', url: '#', price: 200, inStock: true },
        { name: 'Newegg', url: '#', price: 205, inStock: true }
    ],
    rating: 4.5
  },
  {
    id: 'cpu-2',
    name: 'AMD Ryzen 7 7800X3D',
    category: PART_CATEGORY.CPU,
    price: 380,
    image: 'https://picsum.photos/200/200?random=2',
    brand: 'AMD',
    specs: { socket: 'AM5', cores: 8, wattage: 120, memoryType: 'DDR5' },
    vendors: [
        { name: 'Amazon', url: '#', price: 380, inStock: true },
        { name: 'AliExpress', url: '#', price: 360, inStock: true }
    ],
    rating: 4.9
  },
  {
    id: 'cpu-5',
    name: 'Intel Core i9-14900K',
    category: PART_CATEGORY.CPU,
    price: 550,
    image: 'https://picsum.photos/200/200?random=19',
    brand: 'Intel',
    specs: { socket: 'LGA1700', cores: 24, wattage: 253, memoryType: 'DDR5' },
    vendors: [{ name: 'Amazon', url: '#', price: 550, inStock: true }],
    rating: 4.7
  },
  {
    id: 'cpu-3',
    name: 'AMD Threadripper 7960X',
    category: PART_CATEGORY.CPU,
    price: 1450,
    image: 'https://picsum.photos/200/200?random=3',
    brand: 'AMD',
    specs: { socket: 'sTR5', cores: 24, wattage: 350, memoryType: 'DDR5', ecc: true },
    vendors: [{ name: 'Amazon', url: '#', price: 1499, inStock: true }],
    rating: 5.0
  },

  // --- Motherboard ---
  {
    id: 'mobo-entry-1',
    name: 'Gigabyte H610M S2H',
    category: PART_CATEGORY.MAINBOARD,
    price: 85,
    image: 'https://picsum.photos/200/200?random=102',
    brand: 'Gigabyte',
    specs: { socket: 'LGA1700', chipset: 'H610', memoryType: 'DDR4', formFactor: 'mATX' },
    vendors: [{ name: 'Amazon', url: '#', price: 85, inStock: true }],
    rating: 4.0
  },
  {
    id: 'mobo-1',
    name: 'MSI B760 Gaming Plus WiFi',
    category: PART_CATEGORY.MAINBOARD,
    price: 155,
    image: 'https://picsum.photos/200/200?random=5',
    brand: 'MSI',
    specs: { socket: 'LGA1700', chipset: 'B760', memoryType: 'DDR5', formFactor: 'ATX' },
    vendors: [{ name: 'Amazon', url: '#', price: 160, inStock: true }],
    rating: 4.3
  },
  {
    id: 'mobo-2',
    name: 'ASUS ROG Strix X670E-E',
    category: PART_CATEGORY.MAINBOARD,
    price: 440,
    image: 'https://picsum.photos/200/200?random=6',
    brand: 'ASUS',
    specs: { socket: 'AM5', chipset: 'X670E', memoryType: 'DDR5', formFactor: 'ATX' },
    vendors: [{ name: 'Amazon', url: '#', price: 450, inStock: true }],
    rating: 4.7
  },
  {
    id: 'mobo-3',
    name: 'ASRock TRX50 WS',
    category: PART_CATEGORY.MAINBOARD,
    price: 780,
    image: 'https://picsum.photos/200/200?random=7',
    brand: 'ASRock',
    specs: { socket: 'sTR5', chipset: 'TRX50', memoryType: 'DDR5', ecc: true, formFactor: 'E-ATX' },
    vendors: [{ name: 'Newegg', url: '#', price: 800, inStock: true }],
    rating: 4.9
  },

  // --- GPU (Expanded) ---
  {
    id: 'gpu-entry-1',
    name: 'AMD Radeon RX 6600',
    category: PART_CATEGORY.GPU,
    price: 199,
    image: 'https://picsum.photos/200/200?random=103',
    brand: 'AMD',
    specs: { vram: '8GB', wattage: 132 },
    vendors: [{ name: 'Amazon', url: '#', price: 199, inStock: true }],
    rating: 4.5
  },
  {
    id: 'gpu-1',
    name: 'NVIDIA RTX 4060',
    category: PART_CATEGORY.GPU,
    price: 290,
    image: 'https://picsum.photos/200/200?random=8',
    brand: 'NVIDIA',
    specs: { vram: '8GB', wattage: 115 },
    vendors: [{ name: 'Amazon', url: '#', price: 299, inStock: true }],
    rating: 4.2
  },
  {
    id: 'gpu-4',
    name: 'AMD Radeon RX 7800 XT',
    category: PART_CATEGORY.GPU,
    price: 499,
    image: 'https://picsum.photos/200/200?random=22',
    brand: 'AMD',
    specs: { vram: '16GB', wattage: 263 },
    vendors: [{ name: 'Amazon', url: '#', price: 499, inStock: true }],
    rating: 4.8
  },
  {
    id: 'gpu-2',
    name: 'NVIDIA RTX 4090',
    category: PART_CATEGORY.GPU,
    price: 1650,
    image: 'https://picsum.photos/200/200?random=9',
    brand: 'NVIDIA',
    specs: { vram: '24GB', wattage: 450 },
    vendors: [{ name: 'Amazon', url: '#', price: 1750, inStock: true }],
    rating: 5.0
  },

  // --- RAM ---
  {
    id: 'ram-entry-1',
    name: 'Silicon Power 16GB (2x8GB) DDR4',
    category: PART_CATEGORY.RAM,
    price: 35,
    image: 'https://picsum.photos/200/200?random=104',
    brand: 'Silicon Power',
    specs: { memoryType: 'DDR4', speed: '3200MHz', capacity: '16GB' },
    vendors: [{ name: 'Amazon', url: '#', price: 35, inStock: true }],
    rating: 4.4
  },
  {
    id: 'ram-1',
    name: 'Corsair Vengeance 32GB (2x16GB)',
    category: PART_CATEGORY.RAM,
    price: 105,
    image: 'https://picsum.photos/200/200?random=11',
    brand: 'Corsair',
    specs: { memoryType: 'DDR5', speed: '6000MHz', capacity: '32GB' },
    vendors: [{ name: 'Amazon', url: '#', price: 110, inStock: true }],
    rating: 4.6
  },
  {
    id: 'ram-3',
    name: 'G.Skill Trident Z5 RGB 64GB',
    category: PART_CATEGORY.RAM,
    price: 210,
    image: 'https://picsum.photos/200/200?random=24',
    brand: 'G.Skill',
    specs: { memoryType: 'DDR5', speed: '6400MHz', capacity: '64GB' },
    vendors: [{ name: 'Amazon', url: '#', price: 215, inStock: true }],
    rating: 4.9
  },

  // --- Storage ---
  {
    id: 'ssd-entry-1',
    name: 'Kingston NV2 500GB',
    category: PART_CATEGORY.STORAGE,
    price: 40,
    image: 'https://picsum.photos/200/200?random=105',
    brand: 'Kingston',
    specs: { capacity: '500GB', speed: '3500 MB/s' },
    vendors: [{ name: 'Amazon', url: '#', price: 40, inStock: true }],
    rating: 4.3
  },
  {
    id: 'ssd-1',
    name: 'Samsung 990 Pro 1TB',
    category: PART_CATEGORY.STORAGE,
    price: 110,
    image: 'https://picsum.photos/200/200?random=13',
    brand: 'Samsung',
    specs: { capacity: '1TB', speed: '7450 MB/s' },
    vendors: [{ name: 'Amazon', url: '#', price: 119, inStock: true }],
    rating: 4.9
  },

  // --- PSU ---
  {
    id: 'psu-entry-1',
    name: 'Thermaltake Smart 500W',
    category: PART_CATEGORY.PSU,
    price: 40,
    image: 'https://picsum.photos/200/200?random=106',
    brand: 'Thermaltake',
    specs: { wattage: 500, formFactor: 'ATX' },
    vendors: [{ name: 'Amazon', url: '#', price: 40, inStock: true }],
    rating: 4.1
  },
  {
    id: 'psu-1',
    name: 'Corsair RM850x',
    category: PART_CATEGORY.PSU,
    price: 125,
    image: 'https://picsum.photos/200/200?random=14',
    brand: 'Corsair',
    specs: { wattage: 850, formFactor: 'ATX' },
    vendors: [{ name: 'Amazon', url: '#', price: 130, inStock: true }],
    rating: 4.8
  },
  {
    id: 'psu-2',
    name: 'Seasonic Prime TX-1600',
    category: PART_CATEGORY.PSU,
    price: 430,
    image: 'https://picsum.photos/200/200?random=15',
    brand: 'Seasonic',
    specs: { wattage: 1600, formFactor: 'ATX' },
    vendors: [{ name: 'Amazon', url: '#', price: 450, inStock: true }],
    rating: 5.0
  },

  // --- Case ---
  {
    id: 'case-entry-1',
    name: 'Cooler Master Q300L',
    category: PART_CATEGORY.CASE,
    price: 45,
    image: 'https://picsum.photos/200/200?random=107',
    brand: 'Cooler Master',
    specs: { formFactor: 'mATX' },
    vendors: [{ name: 'Amazon', url: '#', price: 45, inStock: true }],
    rating: 4.3
  },
  {
    id: 'case-1',
    name: 'NZXT H5 Flow',
    category: PART_CATEGORY.CASE,
    price: 90,
    image: 'https://picsum.photos/200/200?random=16',
    brand: 'NZXT',
    specs: { formFactor: 'ATX' },
    vendors: [{ name: 'Amazon', url: '#', price: 95, inStock: true }],
    rating: 4.5
  },
  {
    id: 'case-3',
    name: 'Lian Li O11 Dynamic Evo',
    category: PART_CATEGORY.CASE,
    price: 160,
    image: 'https://picsum.photos/200/200?random=28',
    brand: 'Lian Li',
    specs: { formFactor: 'ATX' },
    vendors: [{ name: 'Newegg', url: '#', price: 160, inStock: true }],
    rating: 4.9
  },

  // --- Cooler ---
  {
    id: 'cool-entry-1',
    name: 'Deepcool AK400',
    category: PART_CATEGORY.COOLER,
    price: 35,
    image: 'https://picsum.photos/200/200?random=108',
    brand: 'Deepcool',
    specs: { socket: 'Universal' },
    vendors: [{ name: 'Amazon', url: '#', price: 35, inStock: true }],
    rating: 4.7
  },
  {
    id: 'cool-1',
    name: 'Noctua NH-D15',
    category: PART_CATEGORY.COOLER,
    price: 110,
    image: 'https://picsum.photos/200/200?random=18',
    brand: 'Noctua',
    specs: { socket: 'Universal' },
    vendors: [{ name: 'Amazon', url: '#', price: 110, inStock: true }],
    rating: 4.9
  },
  {
    id: 'cool-2',
    name: 'NZXT Kraken Elite 360',
    category: PART_CATEGORY.COOLER,
    price: 280,
    image: 'https://picsum.photos/200/200?random=29',
    brand: 'NZXT',
    specs: { socket: 'Universal' },
    vendors: [{ name: 'Amazon', url: '#', price: 280, inStock: true }],
    rating: 4.7
  },

  // --- Monitors (New) ---
  {
    id: 'mon-1',
    name: 'LG 24GN650-B 24" 144Hz',
    category: PART_CATEGORY.MONITOR,
    price: 170,
    image: 'https://picsum.photos/200/200?random=30',
    brand: 'LG',
    specs: { resolution: '1080p', refreshRate: '144Hz', panelType: 'IPS' },
    vendors: [{ name: 'Amazon', url: '#', price: 170, inStock: true }],
    rating: 4.6
  },
  {
    id: 'mon-2',
    name: 'Dell UltraSharp U2723QE 27" 4K',
    category: PART_CATEGORY.MONITOR,
    price: 550,
    image: 'https://picsum.photos/200/200?random=31',
    brand: 'Dell',
    specs: { resolution: '4K', refreshRate: '60Hz', panelType: 'IPS Black' },
    vendors: [{ name: 'Amazon', url: '#', price: 550, inStock: true }],
    rating: 4.8
  },
  {
    id: 'mon-3',
    name: 'Samsung Odyssey G9 OLED',
    category: PART_CATEGORY.MONITOR,
    price: 1200,
    image: 'https://picsum.photos/200/200?random=32',
    brand: 'Samsung',
    specs: { resolution: 'DQHD', refreshRate: '240Hz', panelType: 'OLED' },
    vendors: [{ name: 'Amazon', url: '#', price: 1199, inStock: true }],
    rating: 4.9
  }
];

export const PREBUILT_CONFIGS: PrebuiltConfig[] = [
  {
    id: 'pre-1',
    name: 'Budget 1080p Gamer',
    description: 'Perfect entry-level gaming PC for Esports titles.',
    type: PC_TYPE.GAMING,
    totalPriceEstimate: 515,
    partIds: ['cpu-entry-1', 'mobo-entry-1', 'gpu-entry-1', 'ram-entry-1', 'ssd-entry-1', 'psu-entry-1', 'case-entry-1', 'cool-entry-1'],
    image: 'https://picsum.photos/300/200?random=200'
  },
  {
    id: 'pre-2',
    name: 'Mid-Range Streamer',
    description: 'Solid 1440p gaming and streaming performance.',
    type: PC_TYPE.GAMING,
    totalPriceEstimate: 1400,
    partIds: ['cpu-1', 'mobo-1', 'gpu-4', 'ram-1', 'ssd-1', 'psu-1', 'case-1', 'cool-1'],
    image: 'https://picsum.photos/300/200?random=201'
  },
  {
    id: 'pre-3',
    name: 'Ultimate Creator',
    description: 'Top-tier workstation for 4K editing and 3D rendering.',
    type: PC_TYPE.WORKSTATION,
    totalPriceEstimate: 3600,
    partIds: ['cpu-5', 'mobo-2', 'gpu-2', 'ram-3', 'ssd-1', 'psu-2', 'case-3', 'cool-2'],
    image: 'https://picsum.photos/300/200?random=202'
  }
];
